SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `Profile` ;
DROP TABLE IF EXISTS `Users` ;
DROP TABLE IF EXISTS `Depots` ;
DROP TABLE IF EXISTS `SensorReports`;
DROP TABLE IF EXISTS `Sensors` ;
DROP TABLE IF EXISTS `Companies` ;
SET FOREIGN_KEY_CHECKS = 1;
